import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import { LocationProvider } from "../../../utils/Context";
import StoreProvider from "../StoreProvider";
import UserSetter from "./components/UserSetter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <LocationProvider>
        <UserSetter />
        <Header />
      </LocationProvider>
      {children}
    </div>
  );
}
